# -*- coding: utf-8 -*-
"""SADA_Alert_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WEYxYGm8l4so2rOZYy6-7z9Il1x8qAdQ
"""

##PROJECT SADA

##This code is written for the alert function in project SADA.
#The alert system will display a pop-up message and play a sound when the attention level is low
#However it still requires some modifications to function properly.

##install necessary libraries

!pip install playsound==1.2.2

from IPython.display import display, Javascript
from playsound import playsound
import time

# Global variable to track the last alert time
last_alert_time = None

# Function to check attention levels and trigger alerts
def attention_alert(predicted_labels, sound_file='attention_low.mp3', threshold_time=30):
    global last_alert_time  # Referencing the global variable for last alert time

    for label in predicted_labels:
        if label == "Low":
            # Check if enough time has passed since the last alert (to avoid repeated alerts)
            current_time = time.time()
            if last_alert_time is None or current_time - last_alert_time > threshold_time:
                # Display pop-up alert
                display(Javascript('alert("Attention is Low!");'))

                # Play sound alert
                try:
                    playsound(sound_file)
                except Exception as e:
                    print(f"Error playing sound: {e}")
                    # Fallback sound if the specified sound file doesn't exist
                    try:
                        playsound('fallback_sound.mp3')
                    except Exception as e:
                        print(f"Error with fallback sound: {e}")

                # Update the last alert time
                last_alert_time = current_time
            break  # Exit the loop after the first low attention alert
